[build]
cmd = "echo 'Build skipped - using GitHub Actions artifacts'"
watchPatterns = []

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"